### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by jakirkham** [comment]
This is almost ready. We still need the `cuda-sanitizer-api` package for `linux_ppc64le` to move ahead: https://github.com/conda-forge/cuda-sanitizer-api-feedstock/pull/6#issuecomment-1980585763

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
Travis CI builds didn't trigger on merge. Started [builds manually]( https://app.travis-ci.com/github/conda-forge/cuda-command-line-tools-feedstock/builds/269361293 )

**Comment by jakirkham** [comment]
Packages are up. Still mirroring to CDN

**Pull request merged**
